language: python
python:
    - 3.8.5

cache:
  directories:
  - node_modules

install:
    - pip install -r requirements.txt
    - nvm install 0.37.2
    - export NODE_OPTIONS=--max_old_space_size=4096
    - npm install

script:
  - npm run prettier
  - npm run lint-contracts
  - npm run test
  - npm run test-js
  - npm run analyze-contracts

after_script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls