language: generic
dist: bionic
os: linux

cache:
  pip: true
  directories:
  - node_modules

install:
  - sudo apt-get -y update
  - sudo apt install software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -y update
  - sudo apt-get install python3.8
  - ls -1 /usr/bin/python* | grep '[2-3].[0-9]$'
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
  - python3 --version
  - sudo apt-get install python3-pip python3-setuptools
  - python3 -m pip install -U pip
  - pip3 --version

before_script:
  - pip3 install -r requirements.txt
  - export NODE_OPTIONS=--max_old_space_size=4096
  - npm install

script:
  - npm run prettier
  - npm run lint-contracts
  - npm run test
  - npm run test-js
  - npm run analyze-contracts

after_script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls