language: node_js
arch: amd64
os: linux
dist: xenial
node_js:
  - "10"

cache:
  directories:
  - node_modules

before_install:
  - export NODE_OPTIONS=--max_old_space_size=8192

install:
  - npm install

script:
  - npm run lint-contracts
  - npm run test-js
  - travis_wait 40 node --max-old-space-size=7168 ./node_modules/.bin/truffle run coverage

after_script:
  - cat coverage/lcov.info | coveralls
