language: generic
dist: xenial
os: linux

node_js: lts/*
python: 3

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools

cache:
  pip: true
  directories:
  - node_modules

install:
  - python3 --version
  - pip3 --version

before_script:
  - pip3 install -r requirements.txt
  - export NODE_OPTIONS=--max_old_space_size=4096
  - npm install

script:
  - npm run prettier
  - npm run lint-contracts
  - npm run test
  - npm run test-js
  - npm run analyze-contracts

after_script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls